import { canPerformFinalCourseReview } from "@/lib/final-review-auth";
import { finalReviewTutorRuntimeUrl } from "@/lib/final-review-tutor-url";
import { executeFreeAi } from "@/lib/free-ai-service";
import { requireOrganization } from "@/lib/organization-service";
import { getFinalReviewReadiness } from "@/lib/repositories/final-review-repository";
import { authenticateStudioRequest } from "@/lib/studio-auth";

export const runtime = "nodejs";

type TutorRequest = {
  lessonId?: string;
  prompt?: string;
  reviewMode?: string;
};

type TutorSource = string | { id?: string; title?: string };

type TutorRuntimeResponse = {
  answer?: unknown;
  sources?: unknown;
  limitations?: unknown;
  error?: unknown;
};

function sanitizeSources(value: unknown): TutorSource[] {
  if (!Array.isArray(value)) return [];

  const sanitized: TutorSource[] = [];
  for (const item of value.slice(0, 20)) {
    if (typeof item === "string") {
      const source = item.trim();
      if (source) sanitized.push(source.slice(0, 500));
      continue;
    }
    if (!item || typeof item !== "object" || Array.isArray(item)) continue;

    const record = item as Record<string, unknown>;
    const id = typeof record.id === "string" ? record.id.slice(0, 200) : undefined;
    const title = typeof record.title === "string" ? record.title.slice(0, 500) : undefined;
    if (id || title) sanitized.push({ id, title });
  }
  return sanitized;
}

function sanitizeLimitations(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((item): item is string => typeof item === "string" && item.trim().length > 0)
    .slice(0, 20)
    .map((item) => item.trim().slice(0, 1000));
}

async function localTutorResponse(params: {
  courseSlug: string;
  lesson: unknown;
  prompt: string;
}): Promise<Response> {
  try {
    const result = await executeFreeAi({
      messages: [
        {
          role: "system",
          content: [
            "You are the governed Obserra Academy learner tutor running on local inference.",
            "Answer only from the supplied staged lesson context and clearly identify limitations.",
            "Do not invent citations, authorities, regulations, statistics, cases, or completion claims.",
            "If the supplied context cannot support an answer, say so and identify what evidence is missing.",
            "Return concise professional instructional guidance suitable for an executive learner.",
          ].join(" "),
        },
        {
          role: "user",
          content: JSON.stringify({
            courseSlug: params.courseSlug,
            stagedLessonContext: params.lesson,
            learnerQuestion: params.prompt,
          }, null, 2),
        },
      ],
      temperature: 0.1,
      timeoutMs: 60_000,
    });

    const lessonRecord = params.lesson && typeof params.lesson === "object" && !Array.isArray(params.lesson)
      ? params.lesson as Record<string, unknown>
      : {};
    const sources = sanitizeSources(lessonRecord.sources);
    return Response.json({
      answer: result.content.slice(0, 20_000),
      sources,
      limitations: [
        "Response generated by the configured local zero-cost model from the staged lesson context only.",
        ...(sources.length === 0 ? ["No structured source list was available in the staged lesson context."] : []),
      ],
      runtime: { provider: result.provider, model: result.model, estimatedCostUsd: 0 },
    });
  } catch {
    return Response.json({ error: "The local governed learner tutor runtime is unavailable." }, { status: 503 });
  }
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ courseSlug: string }> },
): Promise<Response> {
  const authentication = await authenticateStudioRequest(request);
  if (!authentication.principal) {
    return Response.json({ error: authentication.reason ?? "Authentication and organization context are required." }, { status: 401 });
  }

  const principal = authentication.principal;
  if (!canPerformFinalCourseReview(principal.actorId, principal.role)) {
    return Response.json({ error: "Owner final review access is required." }, { status: 403 });
  }

  const organization = await requireOrganization(principal.organizationId, principal.identityProvider);
  const { courseSlug } = await params;
  const readiness = await getFinalReviewReadiness(organization.clerkOrganizationId, courseSlug);
  if (!readiness?.ready || !readiness.preview) {
    return Response.json(
      { error: "The exact final learner package is not ready for owner review." },
      { status: 409 },
    );
  }

  let body: TutorRequest;
  try {
    body = await request.json() as TutorRequest;
  } catch {
    return Response.json({ error: "A valid JSON request is required." }, { status: 400 });
  }

  const prompt = body.prompt?.trim();
  const lessonId = body.lessonId?.trim();
  if (!prompt || prompt.length > 2000 || !lessonId || lessonId.length > 300) {
    return Response.json({ error: "A valid lesson and prompt are required." }, { status: 400 });
  }
  const selectedLesson = readiness.preview.lessons.find((lesson) => lesson.id === lessonId);
  if (!selectedLesson) {
    return Response.json({ error: "The selected lesson is not part of the staged final package." }, { status: 400 });
  }

  const runtimeUrl = finalReviewTutorRuntimeUrl(courseSlug);
  if (!runtimeUrl) {
    return localTutorResponse({ courseSlug, lesson: selectedLesson, prompt });
  }

  const serviceToken = process.env.FINAL_REVIEW_TUTOR_SERVICE_TOKEN?.trim();
  try {
    const response = await fetch(runtimeUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        ...(serviceToken ? { Authorization: `Bearer ${serviceToken}` } : {}),
        "X-Obserra-Review-Mode": "owner-final",
        "X-Obserra-Course": courseSlug,
      },
      body: JSON.stringify({
        courseSlug,
        lessonId,
        prompt,
        reviewMode: "owner-final",
        reviewerId: principal.actorId,
      }),
      cache: "no-store",
      signal: AbortSignal.timeout(30_000),
    });

    const payload = await response.json() as TutorRuntimeResponse;
    if (!response.ok) {
      const error = typeof payload.error === "string"
        ? payload.error.slice(0, 1000)
        : "The governed learner tutor runtime rejected the review request.";
      return Response.json({ error }, { status: 502 });
    }

    const answer = typeof payload.answer === "string" ? payload.answer.trim().slice(0, 20_000) : "";
    if (!answer) {
      return Response.json({ error: "The governed learner tutor runtime returned no answer." }, { status: 502 });
    }

    return Response.json({
      answer,
      sources: sanitizeSources(payload.sources),
      limitations: sanitizeLimitations(payload.limitations),
    });
  } catch (error) {
    const message = error instanceof Error && error.name === "TimeoutError"
      ? "The governed learner tutor runtime timed out."
      : "The governed learner tutor runtime is unavailable.";
    return Response.json({ error: message }, { status: 502 });
  }
}
